[package]
name = "nih_plug_webview"
version = "0.1.0"
edition = "2021"
authors = [
    "Jakub Idzik <iglak.me@gmail.com>",
    "Max Huttunen <max.huttunen@gmail.com>",
]
license = "ISC"
description = "An adapter to build webview GUIs with NIH-plug"

[dependencies]
baseview = { git = "https://github.com/RustAudio/baseview.git", rev = "cd4df61" }
crossbeam = "0.8.2"
keyboard-types = "0.6.2"
mime_guess = "2.0.4"
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "40269e1", default-features = false }
serde = "1.0.197"
serde_json = "1.0.115"
wry = "0.45.0"

raw-window-handle = "0.6.2"
raw-window-handle-0-5 = { package = "raw-window-handle", version = "0.5.2" }


[dev-dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "40269e1", features = [
    "standalone",
] }
