[package]
name = "nih_plug_webview"
version = "0.0.0"
edition = "2021"
authors = ["Max Huttunen <max.huttunen@gmail.com>"]
license = "ISC"

description = "An adapter to use webview GUIs with NIH-plug"

[dependencies]
baseview = { workspace = true }
crossbeam = { workspace = true }
keyboard-types = { workspace = true }
mime_guess = { workspace = true }
nih_plug = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wry = { workspace = true }
