imports_granularity = "Crate"

comment_width = 100
wrap_comments = true
format_code_in_doc_comments = true

use_small_heuristics = "Max"
use_field_init_shorthand = true
overflow_delimited_expr = true
